
import Foundation
import UIKit

let kName = "binding"
let kHeader = "header"
let kWidth = "width"
let kMinWidth = "minwidth"
let kMultiline = "isMultiline"
let kAlignment = "alignment"
let kColor = "color"
let kType = "type"
let kSort = "sort"
let kSortAcsend = "sortAscend"
let kSortDefault = "sortDefault"
let kReadOnly = "readonly"
let kFormat = "format"
let kAgg = "aggregate"
let kGroup = "groupLevel"
let kValue = "value"
let kManagerGroup = "groupLevelManager"

struct ColumnData {
    static let inventoryColumns: [[String : Any]] = [
        [kName:"version", kValue: 13],
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"itemCode", kHeader: "Item"],
        [kName:"quantityAvailable", kHeader: "Avail", kType: FilterType.Number.rawValue],
        [kName:"priceCase", kHeader: "Price (c)", kType: FilterType.Number.rawValue],
        [kName:"priceBottle", kHeader: "Price (b)", kType: FilterType.Number.rawValue],
        [kName:"discountCase", kHeader: "Discount (c)", kType: FilterType.Number.rawValue],
        [kName:"discountBottle", kHeader: "Discount (b)", kType: FilterType.Number.rawValue],
        [kName:"discountList", kHeader: "Discounts", kWidth: 100],
        [kName:"quantityOnHand", kHeader: "On Hand", kType: FilterType.Number.rawValue],
        [kName:"onSo", kHeader: "On SO", kType: FilterType.Number.rawValue],
        [kName:"onMo", kHeader: "On MO", kType: FilterType.Number.rawValue],
        [kName:"onBo", kHeader: "On BO", kType: FilterType.Number.rawValue],
        [kName:"onPo", kHeader: "On PO", kAlignment:"right", kWidth: 60, kType: FilterType.Number.rawValue, kSort: "onPoTotal"],
        [kName:"poEta", kHeader: "PO ETA", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poEtaSort"],
        [kName:"poDate", kHeader: "PO Date", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poDateSort"],
        [kName:"receiptDate", kHeader: "Rcpt Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue, kSortAcsend: false],
        [kName:"poComment", kHeader: "Avail. Comment"],
        [kName:"restrictedList", kHeader: "Restrictions", kWidth: 100],
        [kName:"brand", kHeader: "Brand"],
        [kName:"masterVendor", kHeader: "Master Vendor"],
        [kName:"vintage", kHeader: "Vintage"],
        [kName:"size", kHeader: "Size"],
        [kName:"closure", kHeader: "Closure"],
        [kName:"type", kHeader: "Type"],
        [kName:"varietal", kHeader: "Varietal"],
        [kName:"organic", kHeader: "Organic"],
        [kName:"biodynamic", kHeader: "Biodynamic"],
        [kName:"country", kHeader: "Country"],
        [kName:"region", kHeader: "Region"],
        [kName:"appellation", kHeader: "Appellation"],
        [kName:"focus", kHeader:"Focus", kType:FilterType.Bool.rawValue],
        [kName:"upc", kHeader:"UPC"],
        [kName:"scoreList", kHeader:"Scores", kAlignment:"right", kWidth: 200],
        [kName:"regen", kHeader:"Regenerative", kType:FilterType.Bool.rawValue],
        [kName:"nat", kHeader:"Natural", kType:FilterType.Bool.rawValue],
        [kName:"vegan", kHeader:"Vegan", kType:FilterType.Bool.rawValue],
        [kName:"hve", kHeader:"HVE", kType:FilterType.Bool.rawValue]
    ]
    static let accountOrderInventoryColumns: [[String : Any]] = [
        [kName:"version", kValue: 8],
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"itemCode", kHeader: "Item"],
        [kName:"cases", kHeader: "Cases", kType: FilterType.Number.rawValue, kReadOnly: false],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false],
        [kName:"quantityAvailable", kHeader: "Avail", kType: FilterType.Number.rawValue],
        [kName:"priceCase", kHeader: "Price (c)", kType: FilterType.Number.rawValue],
        [kName:"priceBottle", kHeader: "Price (b)", kType: FilterType.Number.rawValue],
        [kName:"discountCase", kHeader: "Discount (c)", kType: FilterType.Number.rawValue],
        [kName:"discountBottle", kHeader: "Discount (b)", kType: FilterType.Number.rawValue],
        [kName:"discountList", kHeader: "Discounts", kWidth: 100],
        [kName:"quantityOnHand", kHeader: "On Hand", kType: FilterType.Number.rawValue],
        [kName:"onSo", kHeader: "On SO", kType: FilterType.Number.rawValue],
        [kName:"onMo", kHeader: "On MO", kType: FilterType.Number.rawValue],
        [kName:"onBo", kHeader: "On BO", kType: FilterType.Number.rawValue],
        [kName:"onPo", kHeader: "On PO", kAlignment:"right", kWidth: 60, kType: FilterType.Number.rawValue, kSort: "onPoTotal"],
        [kName:"poEta", kHeader: "PO ETA", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poEtaSort"],
        [kName:"poDate", kHeader: "PO Date", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poDateSort"],
        [kName:"receiptDate", kHeader: "Rcpt Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue, kSortAcsend: false],
        [kName:"poComment", kHeader: "Avail. Comment"],
        [kName:"restrictedList", kHeader: "Restrictions", kWidth: 100],
        [kName:"brand", kHeader: "Brand"],
        [kName:"masterVendor", kHeader: "Master Vendor"],
        [kName:"vintage", kHeader: "Vintage"],
        [kName:"size", kHeader: "Size"],
        [kName:"closure", kHeader: "Closure"],
        [kName:"type", kHeader: "Type"],
        [kName:"varietal", kHeader: "Varietal"],
        [kName:"organic", kHeader: "Organic"],
        [kName:"biodynamic", kHeader: "Biodynamic"],
        [kName:"country", kHeader: "Country"],
        [kName:"region", kHeader: "Region"],
        [kName:"appellation", kHeader: "Appellation"],
        [kName:"focus", kHeader:"Focus", kType:FilterType.Bool.rawValue],
        [kName:"upc", kHeader:"UPC"],
        [kName:"scoreList", kHeader:"Scores", kAlignment:"right", kWidth: 200],
        [kName:"regen", kHeader:"Regenerative", kType:FilterType.Bool.rawValue],
        [kName:"nat", kHeader:"Natural", kType:FilterType.Bool.rawValue],
        [kName:"vegan", kHeader:"Vegan", kType:FilterType.Bool.rawValue],
        [kName:"hve", kHeader:"HVE", kType:FilterType.Bool.rawValue]
    ]
    static let sampleOrderInventoryColumns: [[String : Any]] = [
        [kName:"version", kValue: 9],
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"itemCode", kHeader: "Item"],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false],
        [kName:"comment", kHeader: "Comment", kReadOnly: false],
        [kName:"quantityAvailable", kHeader: "Avail", kType: FilterType.Number.rawValue],
        [kName:"priceCase", kHeader: "Price (c)", kType: FilterType.Number.rawValue],
        [kName:"priceBottle", kHeader: "Price (b)", kType: FilterType.Number.rawValue],
        [kName:"discountCase", kHeader: "Discount (c)", kType: FilterType.Number.rawValue],
        [kName:"discountBottle", kHeader: "Discount (b)", kType: FilterType.Number.rawValue],
        [kName:"discountList", kHeader: "Discounts", kWidth: 100],
        [kName:"quantityOnHand", kHeader: "On Hand", kType: FilterType.Number.rawValue],
        [kName:"onSo", kHeader: "On SO", kType: FilterType.Number.rawValue],
        [kName:"onMo", kHeader: "On MO", kType: FilterType.Number.rawValue],
        [kName:"onBo", kHeader: "On BO", kType: FilterType.Number.rawValue],
        [kName:"onPo", kHeader: "On PO", kAlignment:"right", kWidth: 60, kType: FilterType.Number.rawValue, kSort: "onPoTotal"],
        [kName:"poEta", kHeader: "PO ETA", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poEtaSort"],
        [kName:"poDate", kHeader: "PO Date", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poDateSort"],
        [kName:"receiptDate", kHeader: "Rcpt Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue, kSortAcsend: false],
        [kName:"poComment", kHeader: "Avail. Comment"],
        [kName:"restrictedList", kHeader: "Restrictions", kWidth: 100],
        [kName:"brand", kHeader: "Brand"],
        [kName:"masterVendor", kHeader: "Master Vendor"],
        [kName:"vintage", kHeader: "Vintage"],
        [kName:"size", kHeader: "Size"],
        [kName:"closure", kHeader: "Closure"],
        [kName:"type", kHeader: "Type"],
        [kName:"varietal", kHeader: "Varietal"],
        [kName:"organic", kHeader: "Organic"],
        [kName:"biodynamic", kHeader: "Biodynamic"],
        [kName:"country", kHeader: "Country"],
        [kName:"region", kHeader: "Region"],
        [kName:"appellation", kHeader: "Appellation"],
        [kName:"focus", kHeader:"Focus", kType:FilterType.Bool.rawValue],
        [kName:"upc", kHeader:"UPC"],
        [kName:"scoreList", kHeader:"Scores", kAlignment:"right", kWidth: 200],
        [kName:"regen", kHeader:"Regenerative", kType:FilterType.Bool.rawValue],
        [kName:"nat", kHeader:"Natural", kType:FilterType.Bool.rawValue],
        [kName:"vegan", kHeader:"Vegan", kType:FilterType.Bool.rawValue],
        [kName:"hve", kHeader:"HVE", kType:FilterType.Bool.rawValue]
    ]
    static let orderHeaderColumns: [[String : Any]] = [
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"itemCode", kHeader: "Item", kAgg: "Count"],
        [kName:"cases", kHeader: "Cases", kType: FilterType.Number.rawValue, kReadOnly: false, kAgg: "Sum"],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false, kAgg: "Sum"],
        [kName:"unitPrice", kHeader: "Price", kType: FilterType.Number.rawValue],
        [kName:"priceTotal", kHeader: "Total", kType: FilterType.Number.rawValue, kFormat: "C", kAgg: "Sum"],
        [kName:"moboString", kHeader: "MOBOs", kType: FilterType.String.rawValue]
    ]
    static let sampleOrderHeaderColumns: [[String : Any]] = [
        [kName:"version", kValue: 2],
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"itemCode", kHeader: "Item", kAgg: "Count"],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false, kAgg: "Sum"],
        [kName:"comment", kHeader: "Comment", kReadOnly: false]
    ]
    static let accountOrderHistoryColumns: [[String : Any]] = [
        [kName:"version", kValue: 9],
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"itemCode", kHeader: "Item"],
        [kName:"cases", kHeader: "Cases", kType: FilterType.Number.rawValue, kReadOnly: false],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false],
        [kName:"lastQuantity", kHeader: "Last Qty", kType: FilterType.Number.rawValue],
        [kName:"lastPrice", kHeader: "Last Price", kType: FilterType.Number.rawValue],
        [kName:"lastDate", kHeader: "Last Date", kType: FilterType.Date.rawValue, kSortAcsend: false, kSortDefault: true],
        [kName:"lastInvoice", kHeader: "Last Invoice"],
        [kName:"quantityAvailable", kHeader: "Avail", kType: FilterType.Number.rawValue],
        [kName:"priceCase", kHeader: "Price (c)", kType: FilterType.Number.rawValue],
        [kName:"priceBottle", kHeader: "Price (b)", kType: FilterType.Number.rawValue],
        [kName:"discountCase", kHeader: "Discount (c)", kType: FilterType.Number.rawValue],
        [kName:"discountBottle", kHeader: "Discount (b)", kType: FilterType.Number.rawValue],
        [kName:"discountList", kHeader: "Discounts", kWidth: 100],
        [kName:"quantityOnHand", kHeader: "On Hand", kType: FilterType.Number.rawValue],
        [kName:"onSo", kHeader: "On SO", kType: FilterType.Number.rawValue],
        [kName:"onMo", kHeader: "On MO", kType: FilterType.Number.rawValue],
        [kName:"onBo", kHeader: "On BO", kType: FilterType.Number.rawValue],
        [kName:"onPo", kHeader: "On PO", kAlignment:"right", kWidth: 60, kType: FilterType.Number.rawValue, kSort: "onPoTotal"],
        [kName:"poEta", kHeader: "PO ETA", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poEtaSort"],
        [kName:"poDate", kHeader: "PO Date", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poDateSort"],
        [kName:"receiptDate", kHeader: "Rcpt Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue, kSortAcsend: false],
        [kName:"poComment", kHeader: "Avail. Comment"],
        [kName:"restrictedList", kHeader: "Restrictions", kWidth: 100],
        [kName:"brand", kHeader: "Brand"],
        [kName:"masterVendor", kHeader: "Master Vendor"],
        [kName:"vintage", kHeader: "Vintage"],
        [kName:"size", kHeader: "Size"],
        [kName:"closure", kHeader: "Closure"],
        [kName:"type", kHeader: "Type"],
        [kName:"varietal", kHeader: "Varietal"],
        [kName:"organic", kHeader: "Organic"],
        [kName:"biodynamic", kHeader: "Biodynamic"],
        [kName:"country", kHeader: "Country"],
        [kName:"region", kHeader: "Region"],
        [kName:"appellation", kHeader: "Appellation"],
        [kName:"focus", kHeader:"Focus", kType:FilterType.Bool.rawValue],
        [kName:"upc", kHeader:"UPC"],
        [kName:"scoreList", kHeader:"Scores", kAlignment:"right", kWidth: 200],
        [kName:"regen", kHeader:"Regenerative", kType:FilterType.Bool.rawValue],
        [kName:"nat", kHeader:"Natural", kType:FilterType.Bool.rawValue],
        [kName:"vegan", kHeader:"Vegan", kType:FilterType.Bool.rawValue],
        [kName:"hve", kHeader:"HVE", kType:FilterType.Bool.rawValue]
    ]
    static let sampleOrderHistoryColumns: [[String : Any]] = [
        [kName:"version", kValue: 10],
        [kName:"itemDescription", kHeader: "Description",  kWidth: 300],
        [kName:"itemCode" as AnyObject, kHeader: "Item" as AnyObject],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false],
        [kName:"comment", kHeader: "Comment", kReadOnly: false],
        [kName:"lastQuantity", kHeader: "Last Qty", kType: FilterType.Number.rawValue],
        [kName:"lastDate", kHeader: "Last Date", kType: FilterType.Date.rawValue, kSortAcsend: false],
        [kName:"quantityAvailable", kHeader: "Avail", kType: FilterType.Number.rawValue],
        [kName:"priceCase", kHeader: "Price (c)", kType: FilterType.Number.rawValue],
        [kName:"priceBottle", kHeader: "Price (b)", kType: FilterType.Number.rawValue],
        [kName:"discountCase", kHeader: "Discount (c)", kType: FilterType.Number.rawValue],
        [kName:"discountBottle", kHeader: "Discount (b)", kType: FilterType.Number.rawValue],
        [kName:"discountList", kHeader: "Discounts", kWidth: 100],
        [kName:"quantityOnHand", kHeader: "On Hand", kType: FilterType.Number.rawValue],
        [kName:"onSo", kHeader: "On SO", kType: FilterType.Number.rawValue],
        [kName:"onMo", kHeader: "On MO", kType: FilterType.Number.rawValue],
        [kName:"onBo", kHeader: "On BO", kType: FilterType.Number.rawValue],
        [kName:"onPo", kHeader: "On PO", kAlignment:"right", kWidth: 60, kType: FilterType.Number.rawValue, kSort: "onPoTotal"],
        [kName:"poEta", kHeader: "PO ETA", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poEtaSort"],
        [kName:"poDate", kHeader: "PO Date", kAlignment:"right", kWidth: 80, kType: FilterType.Date.rawValue, kSort: "poDateSort"],
        [kName:"receiptDate", kHeader: "Rcpt Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue, kSortAcsend: false],
        [kName:"poComment", kHeader: "Avail. Comment"],
        [kName:"restrictedList", kHeader: "Restrictions", kWidth: 100],
        [kName:"brand", kHeader: "Brand"],
        [kName:"masterVendor", kHeader: "Master Vendor"],
        [kName:"vintage", kHeader: "Vintage"],
        [kName:"size", kHeader: "Size"],
        [kName:"closure", kHeader: "Closure"],
        [kName:"type", kHeader: "Type"],
        [kName:"varietal", kHeader: "Varietal"],
        [kName:"organic", kHeader: "Organic"],
        [kName:"biodynamic", kHeader: "Biodynamic"],
        [kName:"country", kHeader: "Country"],
        [kName:"region", kHeader: "Region"],
        [kName:"appellation", kHeader: "Appellation"],
        [kName:"focus", kHeader:"Focus", kType:FilterType.Bool.rawValue],
        [kName:"upc", kHeader:"UPC"],
        [kName:"scoreList", kHeader:"Scores", kAlignment:"right", kWidth: 200],
        [kName:"regen", kHeader:"Regenerative", kType:FilterType.Bool.rawValue],
        [kName:"nat", kHeader:"Natural", kType:FilterType.Bool.rawValue],
        [kName:"vegan", kHeader:"Vegan", kType:FilterType.Bool.rawValue],
        [kName:"hve", kHeader:"HVE", kType:FilterType.Bool.rawValue]
    ]
    static let accountColumns: [[String : Any]] = [
        [kName:"version", kValue: 6],
        [kName:"statusString", kHeader: "Status"],
        [kName:"customerNo", kHeader: "Account #"],
        [kName:"customerName", kHeader: "Account Name", kWidth: 300],
        [kName:"buyer1", kHeader: "Wine Buyer 1"],
        [kName:"buyer1Email", kHeader: "Wine Buyer 1 Email"],
        [kName:"buyer1Phone", kHeader: "Wine Buyer 1 Phone"],
        [kName:"buyer2", kHeader: "Wine Buyer 2"],
        [kName:"buyer2Email", kHeader: "Wine Buyer 2 Email"],
        [kName:"buyer2Phone", kHeader: "Wine Buyer 2 Phone"],
        [kName:"buyer3", kHeader: "Wine Buyer 3"],
        [kName:"buyer3Email", kHeader: "Wine Buyer 3 Email"],
        [kName:"buyer3Phone", kHeader: "Wine Buyer 3 Phone"],
        [kName:"affil", kHeader: "Affiliations"],
        [kName:"coopString", kHeader: "Coops"],
        [kName:"shipVia", kHeader: "Ship Via"],
        [kName:"rep", kHeader: "Rep", kWidth: 45, kManagerGroup: 0],
    ]
    static let orderListColumns: [[String : Any]] = [
        [kName:"version", kValue: 18],
        [kName:"customerName", kHeader: "Account", kWidth: 250, kGroup: 0, kManagerGroup: 3],
        [kName:"orderNo", kHeader: "Order #", kWidth: 60],
        [kName:"orderTypeString", kHeader: "Type", kWidth: 35],
        [kName:"holdCodeString", kHeader: "Hold", kWidth: 45],
        [kName:"orderDate", kHeader: "Order Date", kAlignment:"right", kWidth: 70, kType: FilterType.Date.rawValue],
        [kName:"shipExpireDate", kHeader: "Ship/Exp Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue],
        [kName:"arrivalDate", kHeader: "Arr. Date", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue],
        [kName:"boEta", kHeader: "BO ETA", kAlignment:"right", kWidth: 90, kType: FilterType.Date.rawValue],
        [kName:"shipTo", kHeader: "Ship To"],
        [kName:"itemCode", kHeader: "Item", kWidth: 70],
        [kName:"itemDescription", kHeader: "Description", kWidth: 250],
        [kName:"price", kHeader: "Price", kType: FilterType.Number.rawValue, kWidth: 50],
        [kName:"quantityMas", kHeader: "Qty", kType: FilterType.Number.rawValue, kAgg: "Sum", kWidth: 50],
        [kName:"total", kHeader: "Total", kType: FilterType.Number.rawValue, kAgg: "Sum", kWidth: 50],
        [kName:"comment", kHeader: "Item Comment"],
        [kName:"affiliations", kHeader: "Affiliations"],
        [kName:"rep", kHeader: "Rep", kWidth: 45, kManagerGroup: 2],
        [kName:"territory", kHeader: "Territory", kWidth: 45, kManagerGroup: 1]
    ]
    static let sampleListColumns: [[String : Any]] = [
        [kName:"version", kValue: 6],
        [kName:"shipDate", kHeader: "Date", kAlignment:"right", kWidth: 70, kType: FilterType.Date.rawValue],
        [kName:"orderNo", kHeader: "Order #", kWidth: 60],
        [kName:"itemCode", kHeader: "Item", kWidth: 70],
        [kName:"itemDescription", kHeader: "Description", kWidth: 250],
        [kName:"quantityBottle", kHeader: "Qty (b)", kType: FilterType.Number.rawValue, kAgg: "Sum", kWidth: 50],
        [kName:"comment", kHeader: "Item Comment"],
        [kName:"country", kHeader: "Country"],
        [kName:"region", kHeader: "Region"],
        [kName:"appellation", kHeader: "Appellation"],
        [kName:"brand", kHeader: "Brand"],
        [kName:"masterVendor", kHeader: "Master Vendor"],
        [kName:"focus", kHeader:"Focus", kType:FilterType.Bool.rawValue],
        [kName:"shipToName", kHeader:"Ship To"],
        [kName:"rep", kHeader: "Rep", kWidth: 45, kManagerGroup: 0]
    ]
    static let orderMoboColumns: [[String : Any]] = [
        [kName:"version", kValue: 2],
        [kName:"orderNo", kHeader: "Order #", kWidth: 60],
        [kName:"orderTypeString", kHeader: "Type", kWidth: 33],
        [kName:"expirationDate", kHeader: "Exp Date", kAlignment:"right", kWidth: 75, kType: FilterType.Date.rawValue],
        [kName:"customerName", kHeader: "Account", kWidth: 200],
        [kName:"itemCode", kHeader: "Item", kWidth: 80],
        [kName:"itemDescription", kHeader: "Description", kWidth: 300],
        [kName:"cases", kHeader: "Cases", kType: FilterType.Number.rawValue, kReadOnly: false, kWidth: 40],
        [kName:"bottles", kHeader: "Bottles", kType: FilterType.Number.rawValue, kReadOnly: false, kWidth: 50],
        [kName:"quantity", kHeader: "On MOBO", kType: FilterType.Number.rawValue, kWidth: 70]
    ]
    static let orderSavedColumns: [[String : Any]] = [
        [kName:"saveTime", kHeader: "Save Date", kAlignment:"right", kWidth: 150, kType: FilterType.Date.rawValue, kFormat: "Time"],
        [kName:"shipDate", kHeader: "Ship Date", kAlignment:"right", kWidth: 75, kType: FilterType.Date.rawValue],
        [kName:"customerName", kHeader: "Account", kWidth: 200],
        [kName:"orderType", kHeader: "Order Type"],
        [kName:"total", kHeader: "Quantity", kType: FilterType.Number.rawValue, kWidth: 55],
        [kName:"price", kHeader: "Total", kType: FilterType.Number.rawValue, kWidth: 70]
    ]
}
