//
//  GridRowCol.h
//  FlexGrid
//
//  Copyright (c) GrapeCity, Inc. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "GridRowColCollection.h"

/**
 *  Flags that specify the state of a grid row or column.
 */
typedef NS_ENUM (NSInteger, GridRowColFlags){
    /**
     *  GridRowColFlagsVisible
     */
    GridRowColFlagsVisible = 1,
    /**
     *  GridRowColFlagsAllowResizing
     */
    GridRowColFlagsAllowResizing = 2,
    /**
     *  GridRowColFlagsAllowDragging
     */
    GridRowColFlagsAllowDragging = 4,
    /**
     *  GridRowColFlagsAllowMerging
     */
    GridRowColFlagsAllowMerging = 8,
    /**
     *  GridRowColFlagsAllowSorting
     */
    GridRowColFlagsAllowSorting = 16,
    /**
     *  GridRowColFlagsAutoGenerated
     */
    GridRowColFlagsAutoGenerated = 32,
    /**
     *  GridRowColFlagsCollapsed
     */
    GridRowColFlagsCollapsed = 64,
    /**
     *  GridRowColFlagsParentCollapsed
     */
    GridRowColFlagsParentCollapsed = 128,
    /**
     *  GridRowColFlagsSelected
     */
    GridRowColFlagsSelected = 256,
    /**
     *  GridRowColFlagsReadOnly
     */
    GridRowColFlagsReadOnly = 512,
    /**
     *  GridRowColFlagsHtmlContent
     */
    GridRowColFlagsHtmlContent = 1024,
    /**
     *  GridRowColFlagsWordWrap
     */
    GridRowColFlagsWordWrap = 2048,
    /**
     *  GridRowColFlagsRowDefault
     */
    GridRowColFlagsRowDefault = GridRowColFlagsVisible | GridRowColFlagsAllowResizing,
    /**
     *  GridRowColFlagsColumnDefault
     */
    GridRowColFlagsColumnDefault = GridRowColFlagsVisible | GridRowColFlagsAllowDragging | GridRowColFlagsAllowResizing | GridRowColFlagsAllowSorting
};

/**
 *  Class GridRowCol.
 */
@interface GridRowCol : NSObject

/**
 *  Initialize an object for GridRowCol.
 *
 *  @return an object for GridRowCol.
 */
- (id _Nonnull)init;

/**
 *  Gets or sets whether this row or column is visible.
 */
@property (nonatomic) BOOL visible;

/**
 *  Gets whether this row or column is visible and not collapsed.
 */
@property (readonly) BOOL isVisible;

/**
 *  Gets the position of this row or column.
 */
@property (readonly) int pos;

/**
 *  Gets the index of this row or column in the parent collection.
 */
@property (readonly) int index;

/**
 *  Gets or sets the size of this row or column.
 */
@property (nonatomic) int size;

/**
 *  Gets the render size of this row or column.
 */
@property (readonly) int renderSize;

/**
 *  Gets or sets whether the user can resize this row or column.
 */
@property (nonatomic) BOOL allowResizing;

/**
 *  Gets or sets whether cells in this row or column can be merged.
 */
@property (nonatomic) BOOL allowMerging;

/**
 *  Gets or sets whether this row or column is selected.
 */
@property (nonatomic) BOOL isSelected;

/**
 *  Gets or sets whether cells in this row or column can be edited.
 */
@property (nonatomic) BOOL isReadOnly;

/**
 *  Gets or sets whether cells in this row or column should wrap their content.
 */
@property (nonatomic) BOOL wordWrap;

/**
 *  Gets the FlexGrid that owns this row or column.
 */
@property (readonly) FlexGrid * _Nonnull grid;


@end
